export const ContactsList = [
    {
        name:'Juan Rodriguez',
        telephone: '321123678456',
        email: 'juanrod@gmail.com',
        role: 'Client',
    },
    {
        name:'Luisa García',
        telephone: '3109909191',
        email: 'lugar@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Carlos Gomez',
        telephone: '3119876543',
        email: 'cgomez@gmail.com',
        role: 'Client',
    },
    {
        name: 'Ana María Perez',
        telephone: '3011122233',
        email: 'anaperez@gmail.com',
        role: 'Employee',
    },
    {
        name: 'David Martínez',
        telephone: '3209998877',
        email: 'dmartinez@gmail.com',
        role: 'Client',
    },
    {
        name: 'Isabel Torres',
        telephone: '3134445566',
        email: 'itorres@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Santiago Ramírez',
        telephone: '3219991122',
        email: 'sramirez@gmail.com',
        role: 'Client',
    },
    {
        name: 'Carmen Rojas',
        telephone: '3009988777',
        email: 'crojas@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Andrés Castro',
        telephone: '3123344556',
        email: 'acastro@gmail.com',
        role: 'Client',
    },
    {
        name: 'Marta Herrera',
        telephone: '3108765432',
        email: 'mherrera@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Jorge Salazar',
        telephone: '3203345567',
        email: 'jsalazar@gmail.com',
        role: 'Client',
    },
    {
        name: 'Lucía Mendoza',
        telephone: '3019981122',
        email: 'lmendoza@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Gabriel Ochoa',
        telephone: '3112345678',
        email: 'gochoa@gmail.com',
        role: 'Client',
    },
    {
        name: 'Paola Sánchez',
        telephone: '3151239876',
        email: 'psanchez@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Felipe Reyes',
        telephone: '3187766554',
        email: 'freyes@gmail.com',
        role: 'Client',
    },
    {
        name: 'Laura Muñoz',
        telephone: '3171122334',
        email: 'lmunoz@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Alberto López',
        telephone: '3104455667',
        email: 'alopez@gmail.com',
        role: 'Client',
    },
    {
        name: 'Carolina Mejía',
        telephone: '3207788990',
        email: 'cmejia@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Raúl Pineda',
        telephone: '3118877665',
        email: 'rpineda@gmail.com',
        role: 'Client',
    },
    {
        name: 'Sofía Duarte',
        telephone: '3006677889',
        email: 'sduarte@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Miguel Ángel',
        telephone: '3139988776',
        email: 'mangel@gmail.com',
        role: 'Client',
    },
    {
        name: 'Tatiana Vargas',
        telephone: '3153345566',
        email: 'tvargas@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Roberto Castillo',
        telephone: '3122233445',
        email: 'rcastillo@gmail.com',
        role: 'Client',
    },
    {
        name: 'Daniela Fajardo',
        telephone: '3209987766',
        email: 'dfajardo@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Esteban Gil',
        telephone: '3113345566',
        email: 'egil@gmail.com',
        role: 'Client',
    },
    {
        name: 'Patricia Gómez',
        telephone: '3121122334',
        email: 'pgomez@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Sebastián Valle',
        telephone: '3013345567',
        email: 'svalle@gmail.com',
        role: 'Client',
    },
    {
        name: 'Camila Ortiz',
        telephone: '3186677889',
        email: 'cortiz@gmail.com',
        role: 'Employee',
    },
    {
        name: 'Tomás Ramírez',
        telephone: '3154455667',
        email: 'tramirez@gmail.com',
        role: 'Client',
    },
    {
        name: 'Natalia García',
        telephone: '3109981122',
        email: 'ngarcia@gmail.com',
        role: 'Employee',
    }
]